### ISSUE TITLE
src build hung for over 2 hours, even after namespace deleted

### ISSUE THREAD

**Issue by smarterclayton** [openshift/ci-operator#122]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/20824/pull-ci-origin-e2e-gcp/3138/

```
2018/09/02 01:19:40 Resolved source https://github.com/openshift/origin to master@07c07088, merging: #20824 0907d128 @smarterclayton
2018/09/02 01:19:40 Resolving inputs for the test
2018/09/02 01:19:40 Resolved ci/src-cache-origin:master to sha256:4573cac3532b6fed399f1d78eb287202bdf133511756a70a4a912bbcf8743cf2
2018/09/02 01:19:40 Resolved openshift/centos:7 to sha256:fc2476ccae2a5186313f2d1dadb4a969d6d2d4c6b23fa98b6c7b0a1faad67685
2018/09/02 01:19:40 Resolved inputs, targetting namespace ci-op-7yznljfn
2018/09/02 01:19:40 Running [input:root], [input:os], [release-inputs], src, base, [output:stable:base], bin, rpms, [serve:rpms], base-with-rpms, pod, template-service-broker, cli, hypershift, hyperkube, egress-router, egress-http-proxy, egress-dns-proxy, keepalived-ipfailover, control-plane, tests, deployer, recycler, docker-builder, haproxy-router, f5-router, node, [output:stable:pod], [output:stable:template-service-broker], [output:stable:cli], [output:stable:hypershift], [output:stable:hyperkube], [output:stable:egress-router], [output:stable:egress-http-proxy], [output:stable:egress-dns-proxy], [output:stable:keepalived-ipfailover], [output:stable:control-plane], [output:stable:tests], [output:stable:deployer], [output:stable:recycler], [output:stable:docker-builder], [output:stable:haproxy-router], [output:stable:f5-router], [output:stable:node], [images], e2e-gcp
2018/09/02 01:19:40 Creating namespace ci-op-7yznljfn
2018/09/02 01:19:40 Setting a soft TTL of 1h0m0s for the namespace
2018/09/02 01:19:40 Setting a hard TTL of 12h0m0s for the namespace
2018/09/02 01:19:40 Setting up pipeline imagestream for the test
2018/09/02 01:19:40 Populating secrets for test
2018/09/02 01:19:40 Updated secret e2e-gcp-cluster-profile
2018/09/02 01:19:40 Tagging ci/src-cache-origin:master into pipeline:root
2018/09/02 01:19:40 Tagging openshift/centos:7 into pipeline:os
2018/09/02 01:19:40 Tagged release images from openshift/origin-v3.11:${component}, images will be pullable from registry.svc.ci.openshift.org/ci-op-7yznljfn/stable:${component}
2018/09/02 01:19:40 Building src
SIGABRT: abort
PC=0x459121 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0x19b4048, 0x0, 0x0, 0x0, 0x7ffc00000000, 0x0, 0x0, 0x0, 0x7ffc47e5d4c8, 0x410a8b, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:530 +0x21
runtime.futexsleep(0x19b4048, 0x7ffc00000000, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os_linux.go:45 +0x4b
runtime.notesleep(0x19b4048)
	/usr/local/go/src/runtime/lock_futex.go:151 +0x9b
runtime.stoplockedm()
	/usr/local/go/src/runtime/proc.go:2101 +0x8c
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2493 +0x2da
runtime.park_m(0xc42046fb00)
	/usr/local/go/src/runtime/proc.go:2604 +0xb6
runtime.mcall(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:351 +0x5b

goroutine 1 [select, 131 minutes]:
github.com/openshift/ci-operator/pkg/steps.Run(0x129fe80, 0xc4203a5c40, 0xc420650840, 0x3, 0x4, 0x118ba00, 0xc, 0xc420332240, 0x8f)
	/go/src/github.com/openshift/ci-operator/pkg/steps/run.go:45 +0x548
main.(*options).Run.func3(0xc400000008, 0x12198d8)
	/go/src/github.com/openshift/ci-operator/cmd/ci-operator/main.go:439 +0x5aa
github.com/openshift/ci-operator/pkg/interrupt.(*Handler).Run(0xc4202b38f0, 0xc42047fea8, 0x0, 0x0)
	/go/src/github.com/openshift/ci-operator/pkg/interrupt/interrupt.go:105 +0xff
main.(*options).Run(0xc420142000, 0x0, 0x0)
	/go/src/github.com/openshift/ci-operator/cmd/ci-operator/main.go:405 +0x3b0
main.main()
	/go/src/github.com/openshift/ci-operator/cmd/ci-operator/main.go:150 +0x144

goroutine 5 [chan receive]:
github.com/openshift/ci-operator/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x19b3240)
	/go/src/github.com/openshift/ci-operator/vendor/github.com/golang/glog/glog.go:879 +0x8b
created by github.com/openshift/ci-operator/vendor/github.com/golang/glog.init.0
	/go/src/github.com/openshift/ci-operator/vendor/github.com/golang/glog/glog.go:410 +0x203

goroutine 66 [syscall, 131 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 67 [select, 131 minutes, locked to thread]:
runtime.gopark(0x121b3c0, 0x0, 0x1187d49, 0x6, 0x18, 0x1)
	/usr/local/go/src/runtime/proc.go:291 +0x11a
runtime.selectgo(0xc420468f50, 0xc4200be780)
	/usr/local/go/src/runtime/select.go:392 +0xe50
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:549 +0x1f4
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1

goroutine 6 [chan receive, 131 minutes]:
github.com/openshift/ci-operator/pkg/interrupt.(*Handler).Run.func2(0xc42001ade0, 0xc4202b38f0)
	/go/src/github.com/openshift/ci-operator/pkg/interrupt/interrupt.go:98 +0x3d
created by github.com/openshift/ci-operator/pkg/interrupt.(*Handler).Run
	/go/src/github.com/openshift/ci-operator/pkg/interrupt/interrupt.go:97 +0xcf

goroutine 32 [chan receive, 131 minutes]:
github.com/openshift/ci-operator/vendor/k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1(0x128d920, 0xc420455f20, 0xc420454f90)
	/go/src/github.com/openshift/ci-operator/vendor/k8s.io/client-go/tools/record/event.go:229 +0x98
created by github.com/openshift/ci-operator/vendor/k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher
	/go/src/github.com/openshift/ci-operator/vendor/k8s.io/client-go/tools/record/event.go:226 +0x6e

goroutine 25 [IO wait, 8 minutes]:
internal/poll.runtime_pollWait(0x7f306e935f00, 0x72, 0xc42008b850)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420220618, 0x72, 0xffffffffffffff00, 0x1287ce0, 0x193b5d8)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc420220618, 0xc420774000, 0x8000, 0x8000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420220600, 0xc420774000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc420220600, 0xc420774000, 0x8000, 0x8000, 0x0, 0x8, 0x7ffb)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc42000e008, 0xc420774000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6a
crypto/tls.(*block).readFromUntil(0xc42023c090, 0x7f306e94c338, 0xc42000e008, 0x5, 0xc42000e008, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:493 +0x96
crypto/tls.(*Conn).readRecord(0xc420436000, 0x121b417, 0xc420436120, 0x20)
	/usr/local/go/src/crypto/tls/conn.go:595 +0xe0
crypto/tls.(*Conn).Read(0xc420436000, 0xc420417000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1156 +0x100
bufio.(*Reader).Read(0xc4200a6360, 0xc4203ea2d8, 0x9, 0x9, 0xc42008bcc0, 0x42a52b, 0x18)
	/usr/local/go/src/bufio/bufio.go:216 +0x238
io.ReadAtLeast(0x1285260, 0xc4200a6360, 0xc4203ea2d8, 0x9, 0x9, 0x9, 0xc4203a44e0, 0x43ccd1, 0x32)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x1285260, 0xc4200a6360, 0xc4203ea2d8, 0x9, 0x9, 0x121b468, 0xc42008bd10, 0x46ae63)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/openshift/ci-operator/vendor/golang.org/x/net/http2.readFrameHeader(0xc4203ea2d8, 0x9, 0x9, 0x1285260, 0xc4200a6360, 0x0, 0xc400000000, 0x80a460, 0xc420142528)
	/go/src/github.com/openshift/ci-operator/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/openshift/ci-operator/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc4203ea2a0, 0xc4201f2000, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/ci-operator/vendor/golang.org/x/net/http2/frame.go:492 +0xa4
github.com/openshift/ci-operator/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc42008bfb0, 0x121a550, 0xc4204677b0)
	/go/src/github.com/openshift/ci-operator/vendor/golang.org/x/net/http2/transport.go:1428 +0x8e
github.com/openshift/ci-operator/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc4200fa4e0)
	/go/src/github.com/openshift/ci-operator/vendor/golang.org/x/net/http2/transport.go:1354 +0x76
created by github.com/openshift/ci-operator/vendor/golang.org/x/net/http2.(*Transport).newClientConn
	/go/src/github.com/openshift/ci-operator/vendor/golang.org/x/net/http2/transport.go:579 +0x651

goroutine 31 [chan receive, 131 minutes]:
github.com/openshift/ci-operator/vendor/k8s.io/apimachinery/pkg/watch.(*Broadcaster).loop(0xc4200545c0)
	/go/src/github.com/openshift/ci-operator/vendor/k8s.io/apimachinery/pkg/watch/mux.go:208 +0x57
created by github.com/openshift/ci-operator/vendor/k8s.io/apimachinery/pkg/watch.NewBroadcaster
	/go/src/github.com/openshift/ci-operator/vendor/k8s.io/apimachinery/pkg/watch/mux.go:75 +0xd5

goroutine 114 [semacquire, 131 minutes]:
sync.runtime_Semacquire(0xc4206a4ecc)
	/usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc4206a4ec0)
	/usr/local/go/src/sync/waitgroup.go:129 +0x72
github.com/openshift/ci-operator/pkg/steps.Run.func1(0xc4206a4ec0, 0xc4206da8a0)
	/go/src/github.com/openshift/ci-operator/pkg/steps/run.go:28 +0x2b
created by github.com/openshift/ci-operator/pkg/steps.Run
	/go/src/github.com/openshift/ci-operator/pkg/steps/run.go:27 +0x10a

goroutine 132 [chan receive, 8 minutes]:
github.com/openshift/ci-operator/pkg/steps.waitForBuildOrTimeout(0x12893e0, 0xc42043e3e0, 0xc4206907e0, 0xe, 0x118685f, 0x3, 0xa1dd00, 0x0, 0x0)
	/go/src/github.com/openshift/ci-operator/pkg/steps/source.go:278 +0x5ba
github.com/openshift/ci-operator/pkg/steps.waitForBuild(0x12893e0, 0xc42043e3e0, 0xc4206907e0, 0xe, 0x118685f, 0x3, 0x7f306e9916c8, 0x0)
	/go/src/github.com/openshift/ci-operator/pkg/steps/source.go:227 +0x6a
github.com/openshift/ci-operator/pkg/steps.handleBuild(0x12893e0, 0xc42043e3e0, 0xc420732000, 0x0, 0x1, 0xc42028c4b0)
	/go/src/github.com/openshift/ci-operator/pkg/steps/source.go:222 +0x26d
github.com/openshift/ci-operator/pkg/steps.(*sourceStep).Run(0xc420423ee0, 0x129fe80, 0xc4203a5c40, 0x100000200, 0x0, 0x0)
	/go/src/github.com/openshift/ci-operator/pkg/steps/source.go:114 +0x857
github.com/openshift/ci-operator/pkg/steps.runStep(0x129fe80, 0xc4203a5c40, 0xc4201f3170, 0xc4206da840, 0x0)
	/go/src/github.com/openshift/ci-operator/pkg/steps/run.go:114 +0x92
created by github.com/openshift/ci-operator/pkg/steps.Run
	/go/src/github.com/openshift/ci-operator/pkg/steps/run.go:76 +0x3a1

goroutine 129 [semacquire, 8 minutes]:
sync.runtime_notifyListWait(0xc420142540, 0xc400000002)
	/usr/local/go/src/runtime/sema.go:510 +0x10b
sync.(*Cond).Wait(0xc420142530)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/openshift/ci-operator/vendor/golang.org/x/net/http2.(*pipe).Read(0xc420142528, 0xc4205dd001, 0xdff, 0xdff, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/ci-operator/vendor/golang.org/x/net/http2/pipe.go:64 +0x8f
github.com/openshift/ci-operator/vendor/golang.org/x/net/http2.transportResponseBody.Read(0xc420142500, 0xc4205dd001, 0xdff, 0xdff, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/ci-operator/vendor/golang.org/x/net/http2/transport.go:1674 +0xa1
encoding/json.(*Decoder).refill(0xc4204c6780, 0x84d00a, 0x9)
	/usr/local/go/src/encoding/json/stream.go:159 +0x132
encoding/json.(*Decoder).readValue(0xc4204c6780, 0x0, 0x0, 0x103f3c0)
	/usr/local/go/src/encoding/json/stream.go:134 +0x23d
encoding/json.(*Decoder).Decode(0xc4204c6780, 0x1055dc0, 0xc420656160, 0x452190, 0xc42007b800)
	/usr/local/go/src/encoding/json/stream.go:63 +0x78
github.com/openshift/ci-operator/vendor/k8s.io/apimachinery/pkg/util/framer.(*jsonFrameReader).Read(0xc4201f2ae0, 0xc420737300, 0x1000, 0x1300, 0xc4202d4500, 0x40, 0x38)
	/go/src/github.com/openshift/ci-operator/vendor/k8s.io/apimachinery/pkg/util/framer/framer.go:150 +0x295
github.com/openshift/ci-operator/vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming.(*decoder).Decode(0xc42003a3c0, 0x0, 0x128d360, 0xc4202d4500, 0xa80, 0x12899e0, 0xc42082c298, 0x451fc0, 0xc42082c240)
	/go/src/github.com/openshift/ci-operator/vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming/streaming.go:77 +0x95
github.com/openshift/ci-operator/vendor/k8s.io/client-go/rest/watch.(*Decoder).Decode(0xc4206568e0, 0xc42059ffa8, 0x7, 0x12899e0, 0xc4204f2000, 0x0, 0x0)
	/go/src/github.com/openshift/ci-operator/vendor/k8s.io/client-go/rest/watch/decoder.go:49 +0x7c
github.com/openshift/ci-operator/vendor/k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc4201f2b70)
	/go/src/github.com/openshift/ci-operator/vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go:93 +0x12e
created by github.com/openshift/ci-operator/vendor/k8s.io/apimachinery/pkg/watch.NewStreamWatcher
	/go/src/github.com/openshift/ci-operator/vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go:60 +0xa8

rax    0xca
rbx    0x19b3f00
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x19b4048
rsi    0x0
rbp    0x7ffc47e5d490
rsp    0x7ffc47e5d448
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0xc420468f68
r13    0xff
r14    0xff
r15    0xf
rip    0x459121
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```

**Comment by droslean** [comment]
That does not seem like a ci-operator bug. I am not sure why ci-operator received `SIGABRT` signal, but this can be related also with the bug we had when `ci-ns-ttl-controller` was marking active namespaces for deletion, that it was fixed in [#ci-ns-ttl-controller/2](https://github.com/openshift/ci-ns-ttl-controller/pull/2)

**Comment by droslean** [comment]
I am closing this issue since it was never reported again, also race condition of deleted namespaces by ci-ns-ttl-controller was also fixed.

/close
