### ISSUE TITLE
ci-operator stacktrace on artifact publishing?

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/ci-operator#203]
```
2018/11/09 15:13:24 Resolved source https://github.com/operator-framework/operator-lifecycle-manager to master@c82dca53, merging: #560 b3f46e52 @njhale
2018/11/09 15:13:24 Resolved openshift/release:golang-1.10 to sha256:571702190389462220e31ea84041b2a53e56141e799a56dac73c39ed90e22c70
2018/11/09 15:13:24 Resolved openshift/origin-v4.0:base to sha256:9f831b0d8d1b50c928b84d87cb59ef7c84c58b41462f5e10ba154d7853c45b3a
2018/11/09 15:13:24 Using namespace ci-op-xwxn9k5k
2018/11/09 15:13:24 Running [input:root], [input:base], [release-inputs], src, olm, [output:stable:olm], [images], [release:latest], e2e-aws-olm
2018/11/09 15:13:24 Creating namespace ci-op-xwxn9k5k
2018/11/09 15:13:24 Creating rolebinding for user njhale in namespace ci-op-xwxn9k5k
2018/11/09 15:13:25 Setting a soft TTL of 1h0m0s for the namespace
2018/11/09 15:13:25 Setting a hard TTL of 12h0m0s for the namespace
2018/11/09 15:13:25 Setting up pipeline imagestream for the test
2018/11/09 15:13:25 Populating secrets for test
2018/11/09 15:13:25 Created secret e2e-aws-olm-cluster-profile
2018/11/09 15:13:25 Tagging openshift/release:golang-1.10 into pipeline:root
2018/11/09 15:13:25 Tagging openshift/origin-v4.0:base into pipeline:base
2018/11/09 15:13:25 Tagged release images from openshift/origin-v4.0:${component}, images will be pullable from registry.svc.ci.openshift.org/ci-op-xwxn9k5k/stable:${component}
2018/11/09 15:13:25 Building src
2018/11/09 15:13:51 Build src succeeded after 25s
2018/11/09 15:13:51 Building olm
2018/11/09 15:16:45 Build olm succeeded after 2m53s
2018/11/09 15:16:45 Tagging olm into stable
2018/11/09 15:16:45 All images ready
2018/11/09 15:16:45 Create a new update payload image registry.svc.ci.openshift.org/ci-op-xwxn9k5k/release:latest
2018/11/09 15:16:45 Executing release release-latest
2018/11/09 15:17:49 Container release in pod release-latest completed successfully
2018/11/09 15:17:49 Pod release-latest succeeded after 1m3s
2018/11/09 15:17:49 Copying artifacts from release-latest into /logs/artifacts/release-latest
2018/11/09 15:17:50 Copied 0.88Mi of artifacts from release-latest to /logs/artifacts/release-latest
panic: runtime error: index out of range

goroutine 151 [running]:
github.com/openshift/ci-operator/pkg/steps.waitForPodCompletion(0x1285920, 0xc4204b0a40, 0xc4206668d0, 0xe, 0x1275ee0, 0xc4202bc370, 0x7ffc9bc7401c, 0xf, 0x0, 0xc4207d9520)
	/go/src/github.com/openshift/ci-operator/pkg/steps/template.go:569 +0x2d9
github.com/openshift/ci-operator/pkg/steps.(*podStep).Run(0xc4202c0000, 0x1275c60, 0xc42037b740, 0x0, 0x5, 0xc4207fe200)
	/go/src/github.com/openshift/ci-operator/pkg/steps/test.go:120 +0xc4f
github.com/openshift/ci-operator/pkg/steps/release.(*assembleReleaseStep).Run(0xc4200ce140, 0x1275c60, 0xc42037b740, 0xbef1871771dbe600, 0x2ef8f83c0d, 0x1975400)
	/go/src/github.com/openshift/ci-operator/pkg/steps/release/create_release.go:83 +0x773
github.com/openshift/ci-operator/pkg/steps.runStep(0x1275c60, 0xc42037b740, 0xc4205bdad0, 0xc42056a2a0, 0x0)
	/go/src/github.com/openshift/ci-operator/pkg/steps/run.go:105 +0x92
created by github.com/openshift/ci-operator/pkg/steps.Run
	/go/src/github.com/openshift/ci-operator/pkg/steps/run.go:71 +0x3a1
{"component":"entrypoint","error":"wrapped process failed: exit status 2","level":"error","msg":"Error executing test process","time":"2018-11-09T15:17:54Z"}
```

/cc @smarterclayton

**Comment by smarterclayton** [comment]
Wait, was this different than what Trevor fixed?  It looks almost identical...

**Comment by smarterclayton** [comment]
Also

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_cluster-kube-apiserver-operator/114/pull-ci-openshift-cluster-kube-apiserver-operator-master-images/225

**Comment by smarterclayton** [comment]
I'm reverting the code changes that led to this path for now.  I made some suggestions in the revert Pr - using the artifact notifier will probably be a better path and reduce the complexity of the changes here.  The artifact notifier can then capture the necessary artifacts from successful pods (it gets the info needed) and we won't have to change the pod path.
